dist/add-markers.js
dist/build.js
js/interface/add-markers.js
js/libs/build.js

**Note:** This needs (https://github.com/Fliplet/fliplet-widget-interactive-map/pull/12) merged before reviewing
- Refactor how instances of Fliplet.UI.PanZoom are used - Instead of destroy them we now reuse them
- Allow users to add their initial marker by clicking on the map (Settings)

Tweaks and fixes (3)

---

dist/map-panel.js
js/interface/map-panel.js

- Issue ref: https://github.com/Fliplet/fliplet-studio/issues/3972
When a very large image is added to the component we use the direct URL to show it, so users can place markers. However when we save the component settings, the media file gets added a `?size=large` by the backend which makes the image smaller than it used to be before saving.
This behaviour was messing up the initial coordinates set by the user.
By adding the `?size=large` after getting the image information from the file picker provider we make sure the image is always the same size as the size after saving the component settings.
Maybe this could be done in the backend so that the provider returns the URL with the `?size=large` from the start. cc @squallstar

Fixes bad coordinates on very big images

---

dist/add-markers.js
js/interface/add-markers.js

Issue ref: https://github.com/Fliplet/fliplet-studio/issues/4070
There was an event for assign to each marker that when clicked they would be removed. This serves no purpose, it was probably some legacy function from an idea that got discarded, and therefore we can remove it and it will fix the issue.

Removed pointless function that would remove the marker when clicked on - Settings

---

dist/add-markers.js
js/interface/add-markers.js

Issue ref: https://github.com/Fliplet/fliplet-studio/issues/4186
On the tap handler we were checking if the user was clicking on anything else on the map other than a marker to move the selected marker to that new location.
This just adds the ability to click on markers and all markers have the name as a `data` attribute which we can leverage to find the one to select on the right area.

Allow users to select a marker by clicking on them

---

dist/build.js
dist/interface.js
js/libs/build.js
js/libs/interface.js

Error handling checks that came out from changes for https://github.com/Fliplet/fliplet-studio/issues/4186
With this changes it prevents the user from saving with missing crucial information, but if for some reason that information is still missing we do check in the `build` if that information is there and present to the user an error if it isn't, and we stop the rest of the code from running.
We also check:
1. if there's a map to initialize the PanZoom
2. if the markers have missing info - If they have the user will be informed but that doesn't break anything else it simply won't show the marker

Error handling

---

dist/add-markers.js
dist/build.js
js/interface/add-markers.js
js/libs/build.js

Issue ref: https://github.com/Fliplet/fliplet-studio/issues/4280
After analysing the issue I found out that it's not necessary to set the column names as I can use a flag that already exists.
Also changed the `setTimeout` to an interval loop to check is ready, as the timeout wasn't good enough, sometimes the first map wouldn't initialise.

Fixes and tweaks

---

dist/interface.js
js/config/default-table.js

Issue ref: https://github.com/Fliplet/fliplet-studio/issues/4323
Updated the default column name, this will prevent the code from thinking that column names were changed when the overlay is closed.

Fixes #4323

---

dist/add-markers.js
js/interface/add-markers.js

Issue ref: https://github.com/Fliplet/fliplet-studio/issues/4366
Before we were stopping the commit if there was no entries to be committed, because committing an empty array would ruin the table.
By looking through the code I discovered that `.commit()` also accepts a `columns` parameter, so by using it we can now commit empty array of entries without destroying the table columns.

use .commit() correctly

---

widget.json

Ref: https://github.com/Fliplet/fliplet-studio/issues/4490
- Adding the missing `mediaFile` reference fixes the issue of missing images when cloning apps that contain the Interactive Graphics component.

Adds missing mediaFile reference

---

.gitignore
dist/map-panel.js
dist/marker-panel.js

https://github.com/Fliplet/fliplet-studio/issues/3990
When we are clicking the cancel button we closing only called provider, not an entire widget.

When clicking cancel in a provider it doesn't close the entire widget.

---

css/interface.css

Fliplet/fliplet-studio#4947
Removed padding from the file-picker provider.
Before:
After:

Now padding in file-picker provider is correct

---

.gitignore
css/interface.css

https://github.com/Fliplet/fliplet-studio/issues/4130
https://github.com/Fliplet/fliplet-studio/issues/4131
https://github.com/Fliplet/fliplet-studio/issues/4132
Centralized Marker Styles modal, centralized collapse/expand icon, centralized marker highlights.

Fix IE behavior in Interactive map component

---

css/interface.css

Fliplet/fliplet-studio#4163
Changed z-index of the warning message, so it is now bigger than the "Add a new map" button.

The warning message now does not overlap the "Add a new map" button

---

interface.html

Issue
Fliplet/fliplet-studio#4959
Description
Added "Need help" button.
Backward compatibility

Added Need help button which leads to Flilpet documentations about Interactive graphics

---

dist/add-markers.js
dist/build.js
dist/core.js
dist/interface.js
dist/map-panel.js
dist/marker-panel.js
js/interface/add-markers.js
js/interface/marker-panel.js

Fliplet/fliplet-studio#4820
Added the reloadData method on clicking the marker panel close button.

The marker icons are updated when user closes marker panel

---

css/build.css

Fliplet/fliplet-studio#5001
Added background color to search input.

Input background color is now dark in all browsers 

---

css/build.css

Fliplet/fliplet-studio#5152
Added styling according to Hugo's comments in the issue.

Placeholder height is set to 100%

---

dist/interface.js
js/libs/interface.js

ref https://github.com/Fliplet/fliplet-studio/issues/5147
---
The Data Source created by the Interactive Map could not be used in the app when used as a webapp because of missing permissions: the dataSource does not seem to be in use by the app nor have explicit permissions assigned.

create marker's data source bound appId

---

css/interface.css

https://github.com/Fliplet/fliplet-studio/issues/4964
Icons and buttons are no more cropped in the IE 11

Icons and buttons are no longer cropped in the IE 11

---

css/build.css

https://github.com/Fliplet/fliplet-studio/issues/4807
Allow interactive map work correctly when it placed in the accordion.
https://share.getcloudapp.com/Z4u5P7J4

Allow interactive map work correctly when it placed in the accordion.

---

css/interface.css

https://github.com/Fliplet/fliplet-studio/issues/5731
Added flex 1 to the container that contains markers.

Opening Markers Styles dropdown works correctly

---

dist/add-markers.js
dist/build.js
dist/core.js
dist/interface.js
dist/map-panel.js
dist/marker-panel.js
js/libs/build.js

https://github.com/Fliplet/fliplet-studio/issues/5563
Process the console error from centry-io
With map image
https://share.getcloudapp.com/L1ugyAbW
Without map image
https://share.getcloudapp.com/p9uKBJ22
If users don't set a map image they will see an error when try to change the width.

Process the console error from Sentry

---

dist/add-markers.js
dist/build.js
dist/core.js
dist/interface.js
dist/map-panel.js
dist/marker-panel.js
js/libs/build.js

https://github.com/Fliplet/fliplet-studio/issues/5914
Removed marker default selection
https://streamable.com/a4pv7f
@upplabs-alex-levchenko @YaroslavOvdii

Removed marker default selection

---

dist/add-markers.js
dist/build.js
dist/core.js
dist/interface.js
dist/map-panel.js
dist/marker-panel.js
js/interface/map-panel.js
js/interface/marker-panel.js

https://github.com/Fliplet/fliplet-studio/issues/6232
Allow users to select an icon in the marker styles menu
https://share.getcloudapp.com/nOu8NlOz
@upplabs-alex-levchenko @MaksymShokin 
For this fix to work we need to merge this [PR](https://github.com/Fliplet/fliplet-widget-icon-selector/pull/2) first.

Allow users to select an icon in the marker styles menu

---

dist/add-markers.js
dist/build.js
dist/core.js
dist/interface.js
dist/map-panel.js
dist/marker-panel.js
js/libs/build.js

https://github.com/Fliplet/fliplet-studio/issues/6548
Show correct error message when the user doesn't have permissions to the Data Source.
@upplabs-alex-levchenko

[Fix] Show correct error message when the user doesn't have permissions to the Data Source.

---

dist/interface.js
interface.html
js/libs/interface.js

@sofiiakvasnevska
OD-243 https://weboo.atlassian.net/browse/OD-243
Make `Use this settings` button visible when error holder is shown by adding scroll
https://screencast-o-matic.com/watch/cYlflYNU06
@upplabs-alex-levchenko

OD-243 [Fix] Make Use this settings button visible when error holder is shown
