Fliplet/fliplet-widget-interactive-map

css/build.css, dist/build.js, js/libs/build.js
This PR solves two issues:
- [Long text would get outside of the box](https://github.com/Fliplet/fliplet-studio/issues/3825)
- [You wouldn't be able to correctly select a marker when several had the same name](https://github.com/Fliplet/fliplet-studio/issues/3833)
=> More fixes

dist/build.js, js/libs/build.js
Updated hooks based on the conversation had at https://github.com/Fliplet/fliplet-cli/pull/103
=> Updated hooks

build.html
Issue ref: https://github.com/Fliplet/fliplet-studio/issues/3976
Resolves an issue when a map doesn't have markers, but the search button would still be clickable
=> Hides search when no markers

build.html, dist/build.js, dist/map-panel.js, js/interface/map-panel.js, js/libs/build.js
Issue ref: https://github.com/Fliplet/fliplet-studio/issues/3982
- Fixes an issue with a conflict of two `v-if` props
- Improves the check for a Hook response
=> Fixes and improvements

css/interface.css
Issue ref: https://github.com/Fliplet/fliplet-studio/issues/3969
=> Added darker screen behind the overlay

css/interface.css, dist/interface.js, interface.html, js/libs/interface.js
Issues refs: https://github.com/Fliplet/fliplet-studio/issues/4121 | https://github.com/Fliplet/fliplet-studio/issues/4100
=> Prevent users from saving without an image

dist/interface.js, js/libs/interface.js
Issue ref: https://github.com/Fliplet/fliplet-studio/issues/4140
=> Check if maps have the same name

dist/add-markers.js, js/interface/add-markers.js
Related to this comment on this ticket: https://github.com/Fliplet/fliplet-studio/issues/4323#issuecomment-490890810
This prevents committing any data to the data source if there's nothing to save as this would make the DS empty.
=> Prevents saving with empty data

css/interface.css
Issue ref: https://github.com/Fliplet/fliplet-studio/issues/4305
=> Use ellipsis to limit long names of maps

css/build.css
Issue ref: https://github.com/Fliplet/fliplet-studio/issues/4304
=> Add a color to the input text

dist/build.js, js/libs/build.js
- Adds a Hook handler to reconfigure the Interactive Graphics after the styles are changes in the Appearance settings
=> Listening to styles changed hook

css/build.css
What the title says.
We have tweaked the container sizes to go inline with what the users can change in the appearance settings.
=> Tweak the container sizes

dist/build.js, js/libs/build.js
PanZoom change here: https://github.com/Fliplet/fliplet-api/commit/fed3643f10b57432f6b836bfa8f094b09ca6d1d7
=> Use exposed `refresh()` function from the panzoom instance

dist/interface.js, js/libs/interface.js
https://docs.google.com/spreadsheets/d/1x6jXZBSCZFOKs32fF95HNxDISiS_GFrnDRHv1-U1e8s/edit#gid=0
=> added explicit bundling

dist/interface.js, js/libs/interface.js
Issue ref: https://github.com/Fliplet/fliplet-studio/issues/4140#issuecomment-517665707
- Checks if maps have the same name before saving.
=> Check for map names on save

README.md, css/build.css
ref https://github.com/Fliplet/fliplet-studio/issues/4948
=> fixed css when subclassing the component

dist/build.js, js/libs/build.js
Ref. https://github.com/Fliplet/fliplet-studio/issues/5000
=> Ensures maps and markers are correctly rendered if query doesn't match any markers

dist/add-markers.js, dist/build.js, dist/core.js, dist/interface.js, dist/map-panel.js, dist/marker-panel.js, js/libs/build.js
Ref. https://github.com/Fliplet/fliplet-studio/issues/5438
```js
Fliplet.Hooks.on('flInteractiveGraphicsBeforeRender', function () {
return { selectMarker: false };
});
```
=> Adds hook support for selecting no markers

css/interface.css
Ref. https://github.com/Fliplet/fliplet-studio/issues/5656
=> Fixes an issue where a long list of markers may be cut off

dist/add-markers.js, dist/build.js, dist/core.js, dist/interface.js, dist/map-panel.js, dist/marker-panel.js, js/interface/add-markers.js
@sofiiakvasnevska
OD-277 https://weboo.atlassian.net/browse/OD-277
After clicking `Switch to another data source` data source provider shouldn't disappear
https://screencast-o-matic.com/watch/cYlnoENb0d
@upplabs-alex-levchenko
=> OD-277 [Fix] Missing data source provider in Interactive Map

dist/build.js, js/libs/build.js
Ref. https://weboo.atlassian.net/browse/ID-2259
=> ID-2259 [Fix] Fixes race condition to ensure hooks are triggered after app scripts

dist/build.js, js/libs/build.js
- ID-2259 [Fix] Fixes race condition to ensure hooks are triggered after app scripts #110
=> Release to Production

js/libs/build.js
Resolves conflicts found in https://github.com/Fliplet/fliplet-widget-interactive-map/pull/115
=> Keep master up to date with production

dist/add-markers.js, dist/map-panel.js, js/interface/add-markers.js, js/interface/map-panel.js, js/interface/marker-panel.js
Ref. https://weboo.atlassian.net/browse/ID-2679
=> ID-2679 [Maintenance] Update ESLint config

build.html, dist/build.js, js/libs/build.js
Ref. https://weboo.atlassian.net/browse/ID-2674
=> ID-2674 [Fix] Make PanZoom target specific to widget instance

css/build.css
Ref. https://weboo.atlassian.net/browse/ID-3054
=> ID-3054 [Fix] Remove top safe area offset

dist/add-markers.js, dist/build.js, dist/core.js, dist/interface.js, dist/map-panel.js, dist/marker-panel.js, js/interface/add-markers.js, js/interface/map-panel.js, js/libs/interface.js
- Check if error response is handled
https://weboo.atlassian.net/browse/GD-450
https://github.com/Fliplet/fliplet-studio/pull/7543
=> GD-450 [Feat] Check if error response is handled

dist/add-markers.js, dist/map-panel.js, js/interface/add-markers.js, js/interface/map-panel.js
- Reverts a change made to the use of the data sources `.commit()` function
https://weboo.atlassian.net/browse/ID-3536
=> ID-3536 [FIX] Fixes marker duplication issue

dist/build.js, js/libs/build.js
https://www.loom.com/share/f39ae221af8e481cac324cb72776bf04?sid=dc6ea7d9-3e77-4890-b25e-16eab613bc44
=> ID-4118 [FIX] Ensure to select correct marker when switching between layouts
